name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        env:
          - { CODE_VERSION: 1.48.0, DISPLAY: ':99.0' }
          - { CODE_VERSION: 1.49.0, DISPLAY: ':99.0' }
          - { CODE_VERSION: insiders, DISPLAY: ':99.0' }
    runs-on: ${{ matrix.os }}
    env: ${{ matrix.env }}
    defaults:
      run:
        working-directory: ./helloworld-test-sample
        
    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8.x

    - name: Build project
      run: npm install && npm run compile

    - name: Run tests with coverage
      uses: GabrielBB/xvfb-action@v1.4
      with:
        working-directory: ./helloworld-test-sample
        run: npm run coverage
